# Generated by Django 2.2.10 on 2020-03-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupreceiver',
            name='name',
            field=models.CharField(choices=[('LI', 'OŚWIETLENIE'), ('WM', 'ZESPOŁY WIELOMASZYNOWE'), ('SI', 'SILNIK ELEKTRYCZNY'), ('ENE', 'URZĄDZENIA ENERGOELEKTRONICZNE'), ('PRS', 'URZĄDZENIA PROSTOWNIKOWE'), ('SPA', 'URZĄDZENIA SPAWALNICZE'), ('GR', 'GRZAŁKA')], default='LI', max_length=64, unique=True),
        ),
    ]
