# Generated by Django 2.2.10 on 2020-03-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectiondevices',
            name='kr_factor',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
