# Generated by Django 2.2.10 on 2020-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0002_auto_20200322_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='cable_routing',
            field=models.IntegerField(choices=[(0, 'A1'), (1, 'A2'), (2, 'B1'), (3, 'B2'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F1'), (8, 'F2'), (9, 'F3'), (10, 'G')], default=1),
        ),
        migrations.AlterField(
            model_name='cable',
            name='insulation',
            field=models.IntegerField(choices=[(0, 'PVC'), (1, 'XLPE')], default=0),
        ),
        migrations.AlterField(
            model_name='cable',
            name='material',
            field=models.IntegerField(choices=[(0, 'Al'), (1, 'Cu')], default=1),
        ),
    ]
