# Generated by Django 2.2.10 on 2020-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0003_auto_20200322_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectiondevices',
            name='type',
            field=models.IntegerField(choices=[(0, 'B'), (1, 'C'), (2, 'D'), (3, 'gG'), (4, 'Compact')], default=0),
        ),
    ]
