# Generated by Django 2.2.10 on 2020-03-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0004_auto_20200330_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='group',
        ),
        migrations.AlterField(
            model_name='protectiondevices',
            name='off_time',
            field=models.DecimalField(choices=[(0, 0.2), (1, 0.4), (2, 5)], decimal_places=1, default=5, max_digits=2),
        ),
        migrations.DeleteModel(
            name='GroupReceiver',
        ),
    ]
