# Generated by Django 2.2.10 on 2020-03-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0005_auto_20200331_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='core',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='layer_factor',
        ),
        migrations.RemoveField(
            model_name='cable',
            name='length',
        ),
        migrations.RemoveField(
            model_name='protectiondevices',
            name='k2_factor',
        ),
        migrations.RemoveField(
            model_name='protectiondevices',
            name='kr_factor',
        ),
        migrations.RemoveField(
            model_name='protectiondevices',
            name='off_time',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='circuit_number',
        ),
    ]
