# Generated by Django 2.2.10 on 2020-03-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0006_auto_20200322_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectiondevices',
            name='receivers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='elecCalc.Receiver'),
        ),
    ]
