# Generated by Django 2.2.10 on 2020-03-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0007_auto_20200322_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivers', to='elecCalc.Cable'),
        ),
        migrations.AlterUniqueTogether(
            name='protectiondevices',
            unique_together={('type', 'current')},
        ),
    ]
