# Generated by Django 2.2.10 on 2020-03-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0008_auto_20200322_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectiondevices',
            name='name',
            field=models.CharField(default='wyłacznik', max_length=32),
        ),
    ]
