# Generated by Django 2.2.10 on 2020-03-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0009_protectiondevices_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectiondevices',
            name='name',
            field=models.IntegerField(choices=[(0, 'wyłącznik nadprądowy'), (1, 'wyłącznik selektywny'), (2, 'wyłącznik kompaktowy'), (3, 'wyłącznik powietrzny'), (4, 'wkładka bezpiecznikowa')], default=0),
        ),
    ]
