# Generated by Django 2.2.10 on 2020-03-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0010_auto_20200322_1848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='protectiondevices',
            unique_together=set(),
        ),
    ]
