# Generated by Django 2.2.10 on 2020-03-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0011_auto_20200324_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='receiver',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivers', to='elecCalc.GroupReceiver'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='circuit_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elecCalc.Circuit'),
        ),
    ]
