# Generated by Django 2.2.10 on 2020-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0012_auto_20200402_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='voltage',
            field=models.DecimalField(choices=[('0.23', 0.23), ('0.4', 0.4), ('15', 15)], decimal_places=2, default=1, max_digits=3),
        ),
    ]
