# Generated by Django 2.2.10 on 2020-04-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0013_auto_20200402_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='voltage',
            field=models.DecimalField(choices=[(0.23, 0.23), (0.4, 0.4), (15, 15)], decimal_places=2, default=0.23, max_digits=3),
        ),
    ]
