# Generated by Django 2.2.10 on 2020-04-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0016_auto_20200402_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='voltage',
            field=models.CharField(choices=[(0, 0.23), (1, 0.4), (2, 15)], default=1, max_length=25),
        ),
    ]
