# Generated by Django 2.2.10 on 2020-04-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0020_auto_20200403_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protectiondevices',
            name='receivers',
        ),
        migrations.AddField(
            model_name='protectiondevices',
            name='cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='elecCalc.Cable'),
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
    ]
