# Generated by Django 2.2.10 on 2020-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0022_auto_20200404_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='cable_cross_section',
            field=models.DecimalField(choices=[(0, 1.5), (1, 2.5), (2, 4), (3, 6), (4, 10), (5, 16), (6, 25), (7, 35), (8, 50), (9, 70), (10, 95), (11, 125), (12, 150), (13, 185), (14, 240)], decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cable',
            name='cable_routing',
            field=models.IntegerField(choices=[(0, 'A1'), (1, 'A2'), (2, 'B1'), (3, 'B2'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F1'), (8, 'F2'), (9, 'F3'), (10, 'G')], default=1),
        ),
        migrations.AlterField(
            model_name='cable',
            name='insulation',
            field=models.IntegerField(choices=[(0, 'PVC'), (1, 'XLPE')], default=0),
        ),
        migrations.AlterField(
            model_name='cable',
            name='material',
            field=models.IntegerField(choices=[(0, 'Al'), (1, 'Cu')], default=1),
        ),
        migrations.AlterField(
            model_name='protectiondevices',
            name='current',
            field=models.SmallIntegerField(choices=[(0, 10), (1, 16), (2, 25), (3, 40), (4, 50), (5, 80), (6, 100), (7, 125), (8, 160), (9, 200), (10, 250), (11, 315), (12, 400), (13, 630), (14, 800), (15, 1000), (16, 1250), (17, 1600), (18, 2500), (19, 4000)], default=0),
        ),
        migrations.AlterField(
            model_name='protectiondevices',
            name='name',
            field=models.IntegerField(choices=[(0, 'wyłącznik nadprądowy'), (1, 'wyłącznik selektywny'), (2, 'wyłącznik kompaktowy'), (3, 'wyłącznik powietrzny'), (4, 'wkładka bezpiecznikowa')], default=0),
        ),
        migrations.AlterField(
            model_name='protectiondevices',
            name='type',
            field=models.IntegerField(choices=[(0, 'B'), (1, 'C'), (2, 'D'), (3, 'gG'), (4, 'Compact')], default=0),
        ),
    ]
