# Generated by Django 2.2.10 on 2020-04-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0023_auto_20200404_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='insulation',
            field=models.CharField(choices=[('PVC', 'PVC'), ('XLPE', 'XLPE')], default='PVC', max_length=6),
        ),
    ]
