# Generated by Django 2.2.10 on 2020-04-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0024_auto_20200404_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='cable_cross_section',
            field=models.DecimalField(choices=[('1.5', '1.5'), ('2.5', '2.5'), ('4', '4'), ('6', '6'), ('10', '10'), ('16', '16'), ('25', '25'), ('35', '35'), ('50', '50'), ('70', '70'), ('95', '95'), ('125', '125'), ('150', '150'), ('185', '185'), ('240', '240')], decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cable',
            name='cable_routing',
            field=models.IntegerField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('G', 'G')], default=1),
        ),
        migrations.AlterField(
            model_name='cable',
            name='material',
            field=models.IntegerField(choices=[('Al', 'Al'), ('Cu', 'Cu')], default=1),
        ),
        migrations.AlterField(
            model_name='protectiondevices',
            name='current',
            field=models.SmallIntegerField(choices=[('10', '10'), ('16', '16'), ('25', '25'), ('40', '40'), ('50', '50'), ('80', '80'), ('100', '100'), ('125', '125'), ('160', '160'), ('200', '200'), ('250', '250'), ('315', '315'), ('400', '400'), ('630', '630'), ('800', '800'), ('1000', '1000'), ('1250', '1250'), ('1600', '1600'), ('2500', '2500'), ('4000', '4000')], default=0),
        ),
        migrations.AlterField(
            model_name='protectiondevices',
            name='name',
            field=models.IntegerField(choices=[('WN', 'wyłącznik nadprądowy'), ('WS', 'wyłącznik selektywny'), ('WK', 'wyłącznik kompaktowy'), ('WP', 'wyłącznik powietrzny'), ('B', 'wkładka bezpiecznikowa')], default=0),
        ),
        migrations.AlterField(
            model_name='protectiondevices',
            name='type',
            field=models.IntegerField(choices=[('B', 'B'), ('C', 'C'), ('D', 'D'), ('gG', 'gG'), ('Compact', 'Compact')], default=0),
        ),
    ]
