# Generated by Django 2.2.10 on 2020-04-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0026_auto_20200404_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectiondevices',
            name='current',
            field=models.CharField(choices=[('10', '10'), ('16', '16'), ('25', '25'), ('40', '40'), ('50', '50'), ('80', '80'), ('100', '100'), ('125', '125'), ('160', '160'), ('200', '200'), ('250', '250'), ('315', '315'), ('400', '400'), ('630', '630'), ('800', '800'), ('1000', '1000'), ('1250', '1250'), ('1600', '1600'), ('2500', '2500'), ('4000', '4000')], default='16', max_length=6),
        ),
        migrations.AlterField(
            model_name='protectiondevices',
            name='name',
            field=models.CharField(choices=[('WN', 'wyłącznik nadprądowy'), ('WS', 'wyłącznik selektywny'), ('WK', 'wyłącznik kompaktowy'), ('WP', 'wyłącznik powietrzny'), ('B', 'wkładka bezpiecznikowa')], default='WN', max_length=2),
        ),
    ]
