# Generated by Django 2.2.10 on 2020-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0027_auto_20200404_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cir_number', models.CharField(max_length=12)),
                ('cir_name', models.CharField(max_length=64)),
                ('cir_voltage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cir_power', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cir_cos_fi', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cir_current', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cab_amount', models.IntegerField()),
                ('core_amount', models.IntegerField()),
                ('cab_routing', models.CharField(max_length=2)),
                ('cab_insulation', models.CharField(max_length=4)),
                ('cab_material', models.CharField(max_length=2)),
                ('cab_cable_cross_section', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cab_length', models.IntegerField()),
                ('cab_i_dd', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cab_kc_factor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cab_i_z', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dev_type', models.CharField(max_length=12)),
                ('dev_current', models.IntegerField()),
                ('dev_kr_factor', models.DecimalField(decimal_places=1, max_digits=2)),
                ('dev_i_r', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dev_k2_factor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('dev_i_2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('conditions', models.CharField(max_length=3)),
                ('cab_vol_drop', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
