# Generated by Django 2.2.10 on 2020-04-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0028_calculationresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='conditions',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='dev_k2_factor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='dev_kr_factor',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
