# Generated by Django 2.2.10 on 2020-04-07 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0029_auto_20200405_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationresult',
            name='cab_cable_cross_section',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='cab_insulation',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='cab_material',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='cab_routing',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='dev_current',
        ),
        migrations.RemoveField(
            model_name='calculationresult',
            name='dev_type',
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_cable', to='elecCalc.Cable'),
        ),
        migrations.AddField(
            model_name='calculationresult',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_result', to='elecCalc.ProtectionDevices'),
        ),
    ]
