# Generated by Django 2.2.10 on 2020-04-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0031_auto_20200407_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='cab_cable_cross_section',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='cab_insulation',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='cab_material',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='cab_routing',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='calculationresult',
            name='dev_type',
            field=models.CharField(max_length=12),
        ),
    ]
