# Generated by Django 2.2.10 on 2020-04-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0032_auto_20200407_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
                ('load_loss', models.DecimalField(decimal_places=4, max_digits=5)),
                ('no_load_loss', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reactance', models.DecimalField(decimal_places=4, max_digits=5)),
                ('resistance', models.DecimalField(decimal_places=4, max_digits=5)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformers', to='elecCalc.ProtectionDevices')),
            ],
        ),
    ]
