# Generated by Django 2.2.10 on 2020-04-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0033_transformer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSupplyDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('power', models.IntegerField()),
                ('load_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('no_load_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('reactance', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('resistance', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformers', to='elecCalc.ProtectionDevices')),
            ],
        ),
        migrations.DeleteModel(
            name='Transformer',
        ),
    ]
