# Generated by Django 2.2.10 on 2020-04-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0034_auto_20200407_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(choices=[('100', '100'), ('160', '160'), ('200', '200'), ('250', '250'), ('315', '315'), ('400', '400'), ('500', '500'), ('630', '630'), ('800', '800'), ('1000', '1000'), ('1250', '1250'), ('1600', '1600'), ('2000', '2000'), ('2500', '2500'), ('3150', '3150')], default=630)),
                ('load_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('no_load_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('reactance', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('resistance', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformers', to='elecCalc.ProtectionDevices')),
            ],
        ),
        migrations.DeleteModel(
            name='PowerSupplyDevices',
        ),
    ]
