# Generated by Django 2.2.10 on 2020-04-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0035_auto_20200407_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
