# Generated by Django 2.2.10 on 2020-04-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0036_calculationresult_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='position',
            field=models.IntegerField(unique=True),
        ),
    ]
