# Generated by Django 2.2.10 on 2020-04-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0038_auto_20200410_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='position',
            field=models.IntegerField(unique=True),
        ),
    ]
