# Generated by Django 2.2.10 on 2020-04-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0039_auto_20200410_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='position',
            field=models.IntegerField(),
        ),
    ]
