# Generated by Django 2.2.10 on 2020-04-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0040_auto_20200410_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
