# Generated by Django 2.2.10 on 2020-04-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0041_auto_20200410_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationresult',
            name='position',
        ),
    ]
