# Generated by Django 2.2.10 on 2020-04-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecCalc', '0042_remove_calculationresult_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='position',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
